### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by jeremytammik** [rvestvik/BcfApiExampleClient#2]
i registered with https://bim--it.net to obtain a user name and password to use as the client id and secret.

however, i never get to the stage to enter them.

the application fails with an error message in the line 

```
  login.ShowDialog();
```

the error message says:

Serverfehler in der Anwendung /.
Die Ressource kann nicht gefunden werden.
Beschreibung: HTTP 404. Die gesuchte Ressource oder eine ihrer Abhängigkeiten wurde möglicherweise entfernt, umbenannt oder ist vorübergehend nicht verfügbar. Überprüfen Sie folgende URL, und stellen Sie sicher, dass sie richtig geschrieben wurde.
Angeforderter URL: /bcf/f

please also refer to the attached screen snapshot BcfApiExampleClient_login_error.png showing the error message:

![bcfapiexampleclient_login_error](https://cloud.githubusercontent.com/assets/4264589/15000191/2d201ff2-118e-11e6-9c6b-6d3193812b65.png)

**Comment by GeorgDangl** [comment]
Hi jeremy,
a few things in the Api have changed since the example client was written. I'll see to get a small working example by the weekend.

**Comment by jeremytammik** [comment]
Cool. Thank you. Eagerly awaiting your update  :-)

**Comment by GeorgDangl** [comment]
Hi Jeremy,

in December we had another Hackathon in Munich where Veni Lillkall created a small sample app in C#. [It's available here](https://github.com/BIMit/BCF-Hackathon-Munich/tree/Team_C%23). This might give you some ideas how to use the API itself. Additionally, I've updated this repo so it's working again. It was using hardcoded server endpoints that have been changed, [see here.](https://github.com/rvestvik/BcfApiExampleClient/pull/3)

**Comment by jeremytammik** [comment]
hi georg, thank you very much for your work. i still have the same problem. i deleted my local repository and recloned BcfApiExampleClient from scratch. i installed the nuget package and recompiled, then hit F5 to debug, and see the same message as before:

![bcfapiexampleclient_login_error_2](https://cloud.githubusercontent.com/assets/4264589/15100000/6d3b9216-1566-11e6-8092-8fb0d97dd075.png)

**Comment by jeremytammik** [comment]
fixed after merging.

**Comment by jeremytammik** [comment]
hi georg, taking another look at Veni Lillkall's Munich Hackathon project https://github.com/BIMit/BCF-Hackathon-Munich. can you please explain what it does and how it fits together? i see a master branch and three separate branches for C#, Java and JavaScript. Within C#, I see subfolders for (an?) Droid, iOS and something else. lots of classes, most of them trivial. how do they all fit together? what is the purpose of this? are they supposed to work together? thank you for any clarification you can provide! if i understood what they do, i might be able to integrate them into the Revit version of the sample client to do something useful, https://github.com/jeremytammik/RvtBcfApiExampleClient.
